# Generated by Django 5.1 on 2024-09-03 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='link_destivo',
            new_name='link_destino',
        ),
    ]
