# Generated by Django 5.1 on 2024-09-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_rename_link_destivo_banner_link_destino'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('codigo', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
