# Generated by Django 5.1 on 2024-09-04 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_alter_itemestoque_produto_alter_itemestoque_cor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemestoque',
            old_name='Produto',
            new_name='produto',
        ),
    ]
