# Generated by Django 5.1 on 2024-09-17 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_rename_produto_itemestoque_produto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itenspedido',
            old_name='itemestoque',
            new_name='item_estoque',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.cliente'),
        ),
    ]
