# Generated by Django 5.1 on 2024-09-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0010_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
    ]
